Do not override 'const' qualifier
This has worked so far but with fortified system headers from
Glibc 2.40+ and clang compiler it ends up in compile errors

| In file included from /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/string.h:548:
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/bits/string_fortified.h:77:66: error: pass_object_size attribute only applies to constant pointer arguments
|    77 | __NTH (strcpy (__fortify_clang_overload_arg (char *, __restrict, __dest),
|       |                                                                  ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/bits/string_fortified.h:86:66: error: pass_object_size attribute only applies to constant pointer arguments
|    86 | __NTH (stpcpy (__fortify_clang_overload_arg (char *, __restrict, __dest),
|       |                                                                  ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/bits/string_fortified.h:96:67: error: pass_object_size attribute only applies to constant pointer arguments
|    96 | __NTH (strncpy (__fortify_clang_overload_arg (char *, __restrict, __dest),
|       |                                                                   ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/bits/string_fortified.h:107:56: error: pass_object_size attribute only applies to constant pointer arguments
|   107 | __NTH (stpncpy (__fortify_clang_overload_arg (char *, ,__dest),
|       |                                                        ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/bits/string_fortified.h:136:66: error: pass_object_size attribute only applies to constant pointer arguments
|   136 | __NTH (strcat (__fortify_clang_overload_arg (char *, __restrict, __dest),
|       |                                                                  ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/bits/string_fortified.h:145:67: error: pass_object_size attribute only applies to constant pointer arguments
|   145 | __NTH (strncat (__fortify_clang_overload_arg (char *, __restrict, __dest),
|       |                                                                   ^
| /mnt/b/yoe/master/build/tmp/work/riscv64-yoe-linux/python3-inflate64/1.0.0/recipe-sysroot/usr/include/bits/string_fortified.h:161:67: error: pass_object_size attribute only applies to constant pointer arguments
|   161 | __NTH (strlcpy (__fortify_clang_overload_arg (char *, __restrict, __dest),

Therefore adjust needed places to use const qualifier

Signed-off-by: Khem Raj <raj.khem@gmail.com>